version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-client
    ports:
      - "3001:3000"
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-server
    ports:
      - "3000:3000"